kind: Service
apiVersion: v1
metadata:
  name: kube-scheduler-prometheus-discovery
  namespace: kube-system
  labels:
    component: kube-scheduler
spec:
  ports:
    - name: https-metrics
      protocol: TCP
      port: 10259
      targetPort: 10259
  selector:
    component: kube-scheduler
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
