kind: Service
apiVersion: v1
metadata:
  name: kube-controller-manager-prometheus-discovery
  namespace: kube-system
  labels:
    component: kube-controller-manager
spec:
  ports:
    - name: https-metrics
      protocol: TCP
      port: 10257
      targetPort: 10257
  selector:
    component: kube-controller-manager
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
